default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: mendonomster1_development

test:
  <<: *default
  database: mendonomster1_test

production:
  <<: *default
  database: mendonomster1_production
  # username: mendonomster1
  # password: <%= ENV['MENDONOMSTER1_DATABASE_PASSWORD'] %>
